# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nbM7XMqkBO_3iQPmGodD0VELzI-T3QnT
"""

print("呂柏翰")
print("207")